apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemesh
  namespace: openshift-operators
spec:
  channel: "stable"
  name: servicemeshoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace